from_scratch.sh, pelias-json-configmap.yaml, pelias-pip-service.yaml
This sets up the PIP service for use in Kubernetes. The PIP service is a pretty heavy thing: it requires 6GB of memory minimum, and takes quite a while to start up. During development one of the underlying EBS volumes for one of the cluster nodes ran out of burst performance, so it took almost half an hour for the PIP service to start.
Because it takes so long a [readiness probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-readiness-probes) is used that ensures the pods are not actually sent traffic until fully loaded.
=> PIP Service

from_scratch.sh, pelias-placeholder-service.yaml
The placeholder service was really easy to set up. Downloading the data isn't automatic, but it was possible to put together a simple shell script in an `initContainer` to do it.
The service only needs about 500MB of RAM, so it has very low resource limits and will be easy to squeeze multiple pods for redundancy on almost any Kubernetes cluster!
=> Placeholder Service

elasticsearch/packer/pelias-elasticsearch.json, elasticsearch/terraform/elb.tf, elasticsearch/terraform/iam.tf, elasticsearch/terraform/main.tf, elasticsearch/terraform/security_groups.tf, elasticsearch/terraform/templates/user-data.tpl, elasticsearch/terraform/variables.tf, elasticsearch/terraform/vpc.tf
These code changes allow the Terraform scripts embedded in this repo to be used as a module in another terraform setup, rather than only directly. These scripts are used to spin up an Elasticsearch cluster since running Elasticsearch on Kubernetes is not ideal.
Running them as a module is much more flexible and allows anyone to spin up multiple clusters with different settings more easily.
=> Convert Elasticsearch Terraform scripts to a module

README.md, build/Chart.yaml, build/templates/geonames-import-job.tpl, build/templates/openaddresses-import-job.tpl, build/templates/openstreetmap-import-job.tpl, build/templates/polylines-import-job.tpl, build/templates/schema-create-job.tpl, build/templates/whosonfirst-import-job.tpl, elasticsearch/terraform/main.tf, templates/api-deployment.tpl, templates/configmap.tpl, templates/interpolation-deployment.tpl, templates/pip-deployment.tpl, templates/placeholder-deployment.tpl
This PR adds support for full planet builds within Kubernetes, using all 5 importers.
It requires quite a bit of hardware of course, but with proper resource limits it is no problem at all for Kubernetes to handle.
Numerous tweaks had to be made to support this and are included in this repo.
=> Full Planet build

elasticsearch/packer/scripts/default.sh, elasticsearch/packer/scripts/java.sh, elasticsearch/terraform/iam.tf, elasticsearch/terraform/main.tf, elasticsearch/terraform/templates/s3_policy.json.tpl, elasticsearch/terraform/templates/user-data.tpl, elasticsearch/terraform/variables.tf, elasticsearch/terraform/vpc.tf, templates/api-deployment.tpl, templates/libpostal-deployment.tpl, templates/libpostal-service.tpl, templates/pip-deployment.tpl, templates/placeholder-deployment.tpl
Various improvements added during the process of launching https://geocode.earth
This includes:
* proper IAM setup to read snapshots from an S3 bucket
* ability to customize the amount of instance memory dedicated to the Elasticsearch JVM
* ability to configure which subnets within a VPC are used to launch Elasticsearch instances
=> Improvements

elasticsearch/terraform/main.tf
This requires conditionally disabling EBS optimized instances
=> Support t2 instances for elasticsearch

templates/dashboard-deployment.yaml, templates/dashboard-service.yaml, values.yaml
This allows the [Pelias dashboard](https://github.com/pelias/dashboard) to be set up in Kubernetes.
=> Enable pelias dashboard

elasticsearch/terraform/elb.tf
This allows for better metrics in CloudWatch and hopefully is neutral or positive for performance
=> Switch Elasticsearch ELB to HTTP mode

templates/configmap.tpl, values.yaml
This is rarely needed, but can be useful if the standard "pelias"
Elasticsearch index name is not being used.
=> Add the ability to configure the Elasticsearch index name

elasticsearch/terraform/ami.tf
It is now possible to filter AMIs used to launch the Elasticsearch
instances by a tag. Previously, filtering was done based on a hardcoded
value. A variable to allow configuring the value to filter by existed,
but was not used.
Now it's used, and filtering works properly!
=> Properly setup AMI tag filter

elasticsearch/terraform/templates/user-data.tpl
These help catch and diagnose slow queries.
Ideally the thresholds for logging would be configurable, but for now, set some hopefully reasonable defaults
=> Add Elasticsearch slowlog settings

build/templates/schema-create-job.tpl
The correct tag was being used when _deleting_ the old schema, but not creating the new one 😨
=> fix(schema): use correct docker tagwhen creating schema

elasticsearch/README.md, elasticsearch/terraform/cloud_init.tf, elasticsearch/terraform/iam.tf, elasticsearch/terraform/main.tf, elasticsearch/terraform/templates/load_snapshot.sh.tpl, elasticsearch/terraform/templates/s3_policy.json.tpl, elasticsearch/terraform/templates/setup.sh.tpl, elasticsearch/terraform/templates/user-data.tpl, elasticsearch/terraform/variables.tf
This PR allows for an Elasticsearch snapshot to be loaded automatically as the cluster starts. Very convenient.
=> Support loading Elasticsearch snapshots

elasticsearch/terraform/cloud_init.tf, elasticsearch/terraform/templates/setup.sh.tpl, elasticsearch/terraform/variables.tf
It can be very useful to limit the amount of fielddata that can be loaded. Until we merge https://github.com/pelias/schema/pull/302/files, there can be quite a bit of memory used by fielddata, for no benefit.
=> Allow setting ES fielddata circuit breaker limit

elasticsearch/terraform/templates/load_snapshot.sh.tpl
This helps prevent against any sort of accidental damage:
https://www.elastic.co/guide/en/elasticsearch/reference/2.4/misc-cluster.html#cluster-read-only
Example output:
```
ubuntu@ip-172-20-101-136:~$ curl -XDELETE http://localhost:9200/pelias
{"error":{"root_cause":[{"type":"cluster_block_exception","reason":"blocked by: [FORBIDDEN/6/cluster read-only (api)];"}],"type":"cluster_block_exception","reason":"blocked by: [FORBIDDEN/6/cluster read-only (api)];"},"status":403}
```
With a few more changes like this, we might even be able to make our Elasticsearch clusters @trescube -proof :grin:
=> elasticsearch: make cluster read only after loading snapshot

templates/api-canary-deployment.tpl, templates/api-deployment.tpl
This PR does some renaming of config properties to move all API configuration into its own subproperty. It can now be configured like this:
```
api:
dockerTag: "someBranch"
replicas:4 
...etc
```
Additionally, an `api.canaryDockerTag` configuration option is added. If present, this will set up a second deployment, which is configured with the same labels, and so will be connected to the `api-service` and receive traffic just like the standard API deployment. However, the docker tag and number of replicas can be configured independently. This allows testing code with only a fraction of all traffic.
Connects https://github.com/pelias/kubernetes/issues/50
=> Add a canary API deployment option

elasticsearch/terraform/elb.tf, elasticsearch/terraform/main.tf, elasticsearch/terraform/variables.tf
[AWS Launch Templates](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-launch-templates.html) are AWS's new feature to replace Launch Configurations, with some additional abilities.
They can be used both with an AutoScalingGroup, or with a single instance. In our case a nice additional benefit is it's easier to set tags on an instance.
=> feat(elasticsearch): Switch to launch_template

elasticsearch/terraform/elb.tf, elasticsearch/terraform/main.tf, elasticsearch/terraform/outputs.tf, elasticsearch/terraform/variables.tf
Sometimes, an ELB is unwanted when creating an ES cluster. It might be just for testing, or there might be a single instance and an ELB is not needed.
This allows disabling ELB creation by setting the `elb` variable to false.
=> feat(Elasticsearch): allow disabling ELB

templates/configmap.tpl, values.yaml
Now that https://github.com/pelias/api/pull/1219 is merged, we need to control this parameter in the `pelias.json` configmap.
I can see this starting to get unwieldy over time as we start building more and more config options in, but for now it's fine.
=> Add autocomplete address_exclude setting

templates/interpolation-deployment.tpl, templates/libpostal-deployment.tpl, templates/placeholder-deployment.tpl
Eventually these must be configurable, but for now at least setting `maxUnavailable: 0` is important
=> Add rollingUpdate settings to deployments

templates/libpostal-deployment.tpl, templates/libpostal-service.tpl, values.yaml
Use the standard port from our Docker setup, add liveness/readiness probes.
Most importantly, the new [pelias/libpostal-service](https://github.com/pelias/libpostal-service) container is used
=> Libpostal service improvements

templates/dashboard-deployment.yaml, templates/dashboard-ingress.tpl, templates/dashboard-service.yaml, values.yaml
This adds the option to create an Ingress resource for the Pelias dashboard. By specifying `dahboard.domain`, the ingress will be created and set up properly. Super handy.
=> feat: Dashboard ingress

templates/api-ingress.tpl
This makes it even easier to expose the Pelias API externally!
Set `.Values.api.domain` to the host you want to use, and an Ingress with proper HTTPS tags for kube-lego will be set up automatically.
=> Add optional API ingress

templates/api-canary-deployment.tpl, templates/api-deployment.tpl
The `quote` directive has to come AFTER the default, or the default value will be ignored and an empty (but quoted) string will be used
=> fix(api-template): Fix validation of default requests

elasticsearch/packer/files/elastic_wait.sh, elasticsearch/packer/pelias-elasticsearch.json, elasticsearch/packer/scripts/default.sh, elasticsearch/terraform/templates/load_snapshot.sh.tpl, elasticsearch/terraform/templates/setup.sh.tpl
This WIP PR updates the elasticsearch configuration to work with both `2.4` and `5.6`.
When starting the previously packed AMI `ami-035f0df0234dc6d2d`, elasticsearch would fail to come up and it was difficult to discover and debug errors, I discovered that they were being logged to `/usr/local/var/log/elasticsearch/pelias-dev-es5-test-elasticsearch.log`.
The following settings had to be changed:
- `bootstrap.mlockall` was renamed `bootstrap.memory_lock` in 5.6 - I am detecting the version and using the appropriate variable name.
- memlock is more difficult to achieve using `systemd`, some settings have been added to facilitate this.
- a default config value changed and the regex had to be updated to match both `#MAX_LOCKED_MEMORY=unlimited` and `#MAX_LOCKED_MEMORY=`
- index-level settings …
=> modify configuration to support both elasticsearch versions 2.4 and 5.6

templates/api-deployment.tpl
This helps with A/B testing if using a canary
=> add image annotation to API deployment pods

templates/api-canary-deployment.tpl, templates/api-deployment.tpl
This is useful for quickly knowing which of what might be several recent clusters is in use for a given request
=> Add elasticsearch annotation to API deployments

README.md, build/templates/geonames-import-job.tpl, build/templates/openaddresses-import-job.tpl, build/templates/openstreetmap-import-job.tpl, build/templates/polylines-import-job.tpl, build/templates/schema-create-job.tpl, build/templates/whosonfirst-import-job.tpl, templates/api-canary-deployment.tpl, templates/api-deployment.tpl, templates/configmap.tpl, templates/dashboard-deployment.yaml, templates/interpolation-deployment.tpl, templates/interpolation-pvc.yaml, templates/interpolation-service.tpl, templates/libpostal-deployment.tpl, templates/pip-deployment.tpl, templates/pip-pvc.yaml, templates/pip-service.tpl, templates/placeholder-deployment.tpl, values.yaml
This adds many new configuration values and generally improves our Helm configuration.
- All config values are moved to nested yaml structures, so for example whereas there would previously be config values like `apiReplicas`, `apiDockerTag`, etc, they are now found as `api.replicas`, `api.dockerTag`, and similar. This leads to a much cleaner looking configuration where all services are nicely separated.
- All default config values are now in `values.yaml`, which makes that file a great source of documentation. Previously the defaults were strewn throughout the template files using the `default` function which [Helm recommends you only use for values that have to be computed](https://helm.sh/docs/chart_template_guide/#using-the-default-function)
- Lots more can be configured: the …
=> Helm config improvements

templates/configmap.tpl, values.yaml
Combined with https://github.com/pelias/api/pull/1265, this PR allows configuring or disabling API access logging.
Connects #50
=> feat(api): Allow configuring accessLog setting

elasticsearch/terraform/templates/load_snapshot.sh.tpl, elasticsearch/terraform/templates/setup.sh.tpl
This PR aims to resolve the issue mentioned in #68.
I've added the `--fail` flag to all `curl` commands which means that it will `exit(1)` on any status code gte 400.
I'm assuming this is correct for everything and that we aren't relying on silencing these errors at some point.
I've also removed all `-s` flags from `curl` in order to show more verbose output.
I'm not 100% that this the correct thing to do?
I usually only use that in non-interactive shells to silence the download progress bar.
resolves https://github.com/pelias/kubernetes/issues/68
=> curl: increase verbosity and exit(1) on >=400 status codes

templates/configmap.tpl
This fix allows me to run `helm install --name pelias --namespace pelias . -f values.yaml` without
errors on helm v2.13.1.
=> fix #76: got rid of "attributionURL is not a method but has arguments"

elasticsearch/terraform/cloud_init.tf, elasticsearch/terraform/templates/load_snapshot.sh.tpl, elasticsearch/terraform/variables.tf
These settings configure how much available disk Elasticsearch will
allow itself to use before taking preventative action such as:
- preventing new replica shards from loading on a given node
- making the cluster read only
For Elasticsearch clusters where there is data being written and index
sizes are constantly in flux, it makes sense to have high safety margins
of free disk space.
On the other hand, for clusters initialized from a snapshot that won't
ever change, it's most efficient to allow using all available disk
space.
These settings allow tuning the cluster to fit any usecase along that
spectrum.
See https://www.elastic.co/guide/en/elasticsearch/reference/current/disk-allocator.html
=> feat(elasticsearch): Support disk watermark settings

elasticsearch/terraform/templates/setup.sh.tpl
By default, new Linux filesystems are created with 5% of space reserved for the root user. This makes sense for general cases, and especially for root filesystems, so that non-root users cannot fill up a disk completely.
However, for Elasticsearch data and log volumes, there is generally no reason to essentially throw away 5% of storage capacity, especially for the most common case with Pelias where a snapshot is loaded and then never modified.
=> feat(disk): Reduce reserved disk space

elasticsearch/packer/scripts/java.sh
Oracle recently stopped offering free updates for their 1.8 series JDK. As a result, its not possible to install the version we've been using easily on Ubuntu.
The best free alternative now appears to be OpenJDK.
OpenJDK is not _technically_ the recommended version for Elasticsearch 5, however things will probably be ok. Going forward Elasticsearch 6 formally supports OpenJDK and Elasticsearch 7 actually bundles it, which will make things simpler.
References
- https://www.azul.com/eliminating-java-update-confusion/
- http://www.webupd8.org/2014/03/how-to-install-oracle-java-8-in-debian.html
- https://www.elastic.co/support/matrix#matrix_jvm
=> feat(packer): Use OpenJDK instead of Oracle

elasticsearch/packer/scripts/default.sh, elasticsearch/terraform/templates/load_snapshot.sh.tpl, elasticsearch/terraform/variables.tf
This improvement to the snapshot load scripts allows the snapshot name to be autodetected, saving a lot of manual effort and potential error when creating new clusters.
Now, if the `snapshot_name` variable is omitted, the first snapshot from the snapshot repository will automatically be used. This works well with the best practice we've discovered to keep each snapshot in its own repository (since otherwise it is difficult to separate the snapshots within a single repository).
This change requires `jq` to be installed on the AMIs used for Elasticsearch instances. However we love `jq` and usually end up installing it for many manual or investigative tasks, so having it present all the time is a good idea anyway.
Relevant ES documentation: …
=> Autodetect snapshot name

elasticsearch/terraform/templates/setup.sh.tpl
This allows Elasticsearch instances with local NVMe disks to use those
very fast, local disks. Instance types such as `c5d`, `m5d`, `r5d`, and
`i3` all have them.
These disks should have much faster access and lower latency than EBS
volumes, which are network filesystems.
Note: this change will still require an EBS data volume to be created.
It would be possible to toggle this but it would require a lot of very
convoluted terraform code. For now, a simple workaround is to set the data
volume size to 1GB.
=> Prefer local NVMe disk if found

templates/interpolation-deployment.tpl, templates/libpostal-deployment.tpl, templates/pip-deployment.tpl, templates/placeholder-deployment.tpl, values.yaml
This ensures that `maxSurge`, `maxUnavailable`, and `minReadySeconds` deployment settings are configurable across all deployments.
Connects https://github.com/pelias/kubernetes/issues/50
=> Allow configuring more deployment settings

README.md, values.yaml
Unfortunately the hosting for some planet data that was used by default in the helm chart is not going to be available in the future.
=> Update links to hosted data and announce changes

README.md, templates/api-canary-deployment.tpl, templates/api-deployment.tpl, templates/dashboard-deployment.yaml, templates/interpolation-deployment.tpl, templates/libpostal-deployment.tpl, templates/pip-deployment.tpl, templates/placeholder-deployment.tpl, values.yaml
This PR allows a user to specify a nodeSelector object in the values.yaml file to configure what nodes all of the pods in this chart run on.
=> 94 Support node selector

templates/health-logger-deployment.tpl, values.yaml
This is a [small service](https://github.com/pelias/elasticsearch-health-logger) to poll the status of Elasticsearch and convert it to log entries, which can be used for monitoring.
=> Support elasticsearch-health-logger

templates/interpolation-deployment.tpl
Deploying the interpolation service is too expensive for this
=> Remove configmap checksum annotation from interpolation deployment

templates/interpolation-deployment.tpl, templates/placeholder-deployment.tpl, values.yaml
This PR adds resource requests and limits for [ephemeral storage](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#local-ephemeral-storage) for the Placeholder and Interpolation services.
They both can use quite a bit of disk space, and without setting a reasonable value for the resource request, Kubernetes can get stuck in a loop where it repeatedly tries to launch a pod on a machine that doesn't have enough storage.
The defaults are currently set to 5GB for both services. The interpolation service will need a much bigger limit, at least 50GB, for full planet builds.
=> Ephemeral storage limits

templates/api-canary-deployment.tpl, templates/canary-configmap.json.tpl
This allows for canary API deployments to have any setting in `pelias.json` configured differently from the baseline API deployment.
We will have to add support for more configuration values over time, but for now this allows for setting a different Elasticsearch host, which makes it easy to test two different Elasticsearch clusters at the same time.
For @geocodeearth, we plan to use this to test the roll out of Elasticsearch 6.
=> Use a separate configmap for canary deployments

templates/api-canary-deployment.tpl, templates/api-deployment.tpl, templates/dashboard-deployment.yaml, templates/health-logger-deployment.tpl, templates/interpolation-deployment.tpl, templates/libpostal-deployment.tpl, templates/pip-deployment.tpl, templates/placeholder-deployment.tpl
:wave: I did some ~awesome~ minimal work for the Pelias project and would love for everyone to have a look at it and provide feedback.
---
- Initial hack at #111 
---
---
I tested very briefly via deployment to minikube: 
```bash
minikube start
helm install --name pelias --namespace pelias ./ -f ./values.yaml
```
This results in a success message.
=> Upgrade Helm charts for Kubernetes 1.16 compatibility.

templates/interpolation-deployment.tpl, templates/placeholder-deployment.tpl
These images have up to date, full, versions of both `wget` and `curl`.
In testing, it turns out that the busybox version of `wget` will max out a CPU when downloading at only around 50MB/sec, whereas the full version can handle almost 100MB/sec with minimal CPU usage.
=> Use Pelias images instead of busybox

templates/pip-deployment.tpl, values.yaml
The PIP service needs to download a lot of data so it definitely can benefit from ephemeral storage limits. This change adds the ability to configure them, as https://github.com/pelias/kubernetes/pull/113 did for Placeholder and interpolation.
The default is sufficient for a full planet download.
=> Set up ephemeral storage resource limits for PIP

templates/pip-deployment.tpl, values.yaml
This PR allows the CPU and memory resource limits to be configured for the PIP service.
The default values are now config driven but are unchanged.
Connects https://github.com/pelias/kubernetes/issues/50
=> Allow configuring cpu/memory limits for PIP

templates/interpolation-deployment.tpl, templates/pip-deployment.tpl, templates/placeholder-deployment.tpl, values.yaml
This allows the download commands to be completely customized.
In order for this to work, the commands have been modified to use an environment variable for either the download URL or download path (depending on how many files need to be downloaded).
No functional changes to the downloads have been made.
Note that YAML formatting might be critical here, the following guide is helpful: https://yaml-multiline.info/
=> Extract download commands to values.yaml

values.yaml
As of https://github.com/pelias/kubernetes/pull/115, an entry (even just `null`) was required for the canary.elasticsearch value in order to avoid an error.
The defaults should work out of the box, so this sets a default value for `canary.elasticsearch.host` to prevent the error.
=> Add empty value for default canary elasticsearch host

values.yaml
Looks like some default setting values were missed back in
https://github.com/pelias/kubernetes/pull/91
This was causing undesirable defaults for these values.
=> Add missing default values for libpostal-service configuration

Dockerfile
`python-pip` is no longer available for `ubuntu:latest`. This PR migrates to pip3.
=> Install and use pip3

templates/api-canary-deployment.tpl, templates/api-deployment.tpl, templates/api-service.tpl, templates/dashboard-deployment.yaml, templates/health-logger-deployment.tpl, templates/interpolation-deployment.tpl, templates/libpostal-deployment.tpl, templates/pip-deployment.tpl, templates/placeholder-deployment.tpl
This is required in newer versions of Kubernetes.
Our API canary setup makes this _slightly_ trickier than normal, but it's not too bad.
=> Add `selector.matchLabels`

templates/canary-configmap.json.tpl, templates/configmap.tpl, values.yaml
This [API](https://github.com/pelias/api#configuration-via-pelias-config) configuration option is useful with custom data.
In the future, we may change the default (from false to true), so this PR does not set a default value of its own.
=> feat: allow specifying `api.targets.auto_discover`

templates/dashboard-deployment.yaml
This variable is no longer used after https://github.com/pelias/dashboard/pull/18
=> Remove dashboard `AUTH_TOKEN` envar

templates/canary-configmap.json.tpl, templates/configmap.tpl
This flag was deprecated in https://github.com/pelias/whosonfirst/pull/503, and is no longer allowed in `pelias.json`
=> fix: remove importVenues flag
